In [2]:
import pandas as pd
from pathlib import Path

In [9]:
base_dir = Path('food_data')


food_categories_code = ['0200', # Spices and Herbs
                        '0900', # Fruits and Fruit Juices
                        '1100', # Vegetables and Vegetable Products
                        '1200', # Nut and Seed Products
                        '1600', # Legumes and Legume Products
                        '2000'  # Cereal Grains and Pasta
                        ]


food_categories_id = [2, # Spices and Herbs
                      9, # Fruits and Fruit Juices
                      11, # Vegetables and Vegetable Products
                      12, # Nut and Seed Products
                      16, # Legumes and Legume Products
                      20  # Cereal Grains and Pasta
                     ]

In [10]:
food_df = pd.read_csv(base_dir / 'food.csv')
food_df.head()

,fdc_id,data_type,description,food_category_id,publication_date
0,346464,branded_food,WOLF Chili Without Beans,NaN,2019-04-01
1,346470,branded_food,"WOLF BRAND Hot Chili Without Beans, 106 oz., 1...",NaN,2019-04-01
2,346519,branded_food,"SANALAC Non Fat Dry Milk, 1 QT",NaN,2019-04-01
3,346520,branded_food,SWISS MISS Hot Cocoa Mix Dark Chocolate Sensat...,NaN,2019-04-01
4,346532,branded_food,"SWISS MISS Creamy Vanilla Pudding, 24 OZ",NaN,2019-04-01

In [12]:
food_df = food_df[food_df['data_type'] == 'foundation_food']
food_df = food_df[food_df['food_category_id'].isin(food_categories_id)]
food_df.head()

,fdc_id,data_type,description,food_category_id,publication_date
297000,321358,foundation_food,"Hummus, commercial",16.0,2019-04-01
297001,321360,foundation_food,"Tomatoes, grape, raw",11.0,2019-04-01
297002,321611,foundation_food,"Beans, snap, green, canned, regular pack, drai...",11.0,2019-04-01
297004,323294,foundation_food,"Nuts, almonds, dry roasted, with salt added",12.0,2019-04-01
297005,323505,foundation_food,"Kale, raw",11.0,2019-04-01

In [14]:
hummus_fdc_id = 321358

n_lookup_df = pd.read_csv(base_dir / 'food_nutrient.csv')
n_lookup_df.head()

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
0,4180087,346464,1087,16.00,NaN,75.0,NaN,NaN,NaN,NaN,NaN
1,4180088,346464,1089,0.73,NaN,75.0,NaN,NaN,NaN,NaN,NaN
2,4180089,346464,1104,0.00,NaN,75.0,NaN,NaN,NaN,NaN,NaN
3,4180090,346464,1110,0.00,NaN,75.0,NaN,NaN,NaN,NaN,NaN
4,4180091,346464,1162,0.50,NaN,75.0,NaN,NaN,NaN,NaN,NaN

In [56]:
nutrient_hummus = n_lookup_df[n_lookup_df['fdc_id'] == hummus_fdc_id]
nutrient_hummus.head()

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
4014756,2219707,321358,1120,3.0,1.0,1.0,NaN,NaN,3.00,NaN,2015.0
4014757,2219708,321358,1122,0.0,1.0,1.0,NaN,NaN,0.00,NaN,2015.0
4014758,2219709,321358,1127,1.3,6.0,1.0,0.26,2.47,1.21,NaN,2015.0
4014759,2219710,321358,1130,0.0,6.0,1.0,0.00,0.00,0.00,NaN,2015.0
4014760,2219711,321358,1131,0.0,6.0,1.0,0.00,0.00,0.00,NaN,2015.0

In [19]:
nutrients = pd.read_csv(base_dir / 'nutrient.csv')
print(len(nutrients))
nutrients.head()

232

     id                         name unit_name  nutrient_nbr    rank
0  1002                     Nitrogen         G         202.0   500.0
1  1003                      Protein         G         203.0   600.0
2  1004            Total lipid (fat)         G         204.0   800.0
3  1005  Carbohydrate, by difference         G         205.0  1110.0
4  1007                          Ash         G         207.0  1000.0

In [20]:
nutrients.unit_name.unique()

array(['G', 'KCAL', 'SP_GR', 'MG', 'kJ', 'UG', 'IU', 'MG_ATE'],
      dtype=object)

In [30]:
pd.set_option('display.max_rows', None)
nutrients

   1079                      Fiber, total dietary         G         291.0
27   1081                                    Ribose         G         294.0
28   1082                            Fiber, soluble         G         295.0
29   1084                          Fiber, insoluble         G         297.0
30   1085                          Total fat (NLEA)         G         298.0
31   1086                      Total sugar alcohols         G         299.0
32   1087                               Calcium, Ca        MG         301.0
33   1088                              Chlorine, Cl        MG         302.0
34   1089                                  Iron, Fe        MG         303.0
35   1090                             Magnesium, Mg        MG         304.0
36   1091                             Phosphorus, P        MG         305.0
37   1092                              Potassium, K        MG         306.0
38   1093                                Sodium, Na        MG         307.0
39   1094                                 Sulfur, S        MG         308.0
40   1095                                  Zinc, Zn        MG         309.0
41   1096                              Chromium, Cr        UG         310.0
42   1097                                Cobalt, Co        UG         311.0
43   1098                                Copper, Cu        MG         312.0
44   1099                               Fluoride, F        UG         313.0
45   1100                                 Iodine, I        UG         314.0
46   1101                             Manganese, Mn        MG         315.0
47   1102                            Molybdenum, Mo        UG         316.0
48   1103                              Selenium, Se        UG         317.0
49   1104                             Vitamin A, IU        IU         318.0
50   1105                                   Retinol        UG         319.0
51   1106                            Vitamin A, RAE        UG         320.0
52   1107                            Carotene, beta        UG         321.0
53   1108                           Carotene, alpha        UG         322.0
54   1109              Vitamin E (alpha-tocopherol)        MG         323.0
55   1110  Vitamin D (D2 + D3), International Units        IU         324.0
56   1111               Vitamin D2 (ergocalciferol)        UG         325.0
57   1112              Vitamin D3 (cholecalciferol)        UG         326.0
58   1113                 25-hydroxycholecalciferol        UG         327.0
59   1114                       Vitamin D (D2 + D3)        UG         328.0
60   1116                                  Phytoene        UG         330.0
61   1117                               Phytofluene        UG         331.0
62   1119                                Zeaxanthin        UG         338.2
63   1120                       Cryptoxanthin, beta        UG         334.0
64   1121                                    Lutein        UG         338.1
65   1122                                  Lycopene        UG         337.0
66   1123                       Lutein + zeaxanthin        UG         338.0
67   1124         Vitamin E (label entry primarily)        IU         340.0
68   1125                          Tocopherol, beta        MG         341.0
69   1126                         Tocopherol, gamma        MG         342.0
70   1127                         Tocopherol, delta        MG         343.0
71   1128                        Tocotrienol, alpha        MG         344.0
72   1129                         Tocotrienol, beta        MG         345.0
73   1130                        Tocotrienol, gamma        MG         346.0
74   1131                        Tocotrienol, delta        MG         347.0
75   1137                                  Boron, B        UG         354.0
76   1146                                Nickel, Ni        UG         371.0
77   1158                                 Vitamin E    MG_ATE         394.0
78   1159                         cis-beta-Carotene        UG         321.1
79   1160                              cis-Lycopene        UG         337.1
80   1161                     cis-Lutein/Zeaxanthin        UG         338.3
81   1162            Vitamin C, total ascorbic acid        MG         401.0
82   1165                                   Thiamin        MG         404.0
83   1166                                Riboflavin        MG         405.0
84   1167                                    Niacin        MG         406.0
85   1170                          Pantothenic acid        MG         410.0
86   1175                               Vitamin B-6        MG         415.0
87   1176                                    Biotin        UG         416.0
88   1177                             Folate, total        UG         417.0
89   1178                              Vitamin B-12        UG         418.0
90   1180                            Choline, total        MG         421.0
91   1181                                  Inositol        MG         422.0
92   1183                 Vitamin K (Menaquinone-4)        UG         428.0
93   1184          Vitamin K (Dihydrophylloquinone)        UG         429.0
94   1185                 Vitamin K (phylloquinone)        UG         430.0
95   1186                                Folic acid        UG         431.0
96   1187                              Folate, food        UG         432.0
97   1188        5-methyl tetrahydrofolate (5-MTHF)        UG         433.0
98   1190                               Folate, DFE        UG         435.0
99   1191            10-Formyl folic acid (10HCOFA)        UG         436.0
100  1192     5-Formyltetrahydrofolic acid (5-HCOH4        UG         437.0
101  1194                             Choline, free        MG         450.0
102  1195              Choline, from phosphocholine        MG         451.0
103  1196        Choline, from phosphotidyl choline        MG         452.0
104  1197       Choline, from glycerophosphocholine        MG         453.0
105  1198                                   Betaine        MG         454.0
106  1199               Choline, from sphingomyelin        MG         455.0
107  1210                                Tryptophan         G         501.0
108  1211                                 Threonine         G         502.0
109  1212                                Isoleucine         G         503.0
110  1213                                   Leucine         G         504.0
111  1214                                    Lysine         G         505.0
112  1215                                Methionine         G         506.0
113  1216                                   Cystine         G         507.0
114  1217                             Phenylalanine         G         508.0
115  1218                                  Tyrosine         G         509.0
116  1219                                    Valine         G         510.0
117  1220                                  Arginine         G         511.0
118  1221                                 Histidine         G         512.0
119  1222                                   Alanine         G         513.0
120  1223                             Aspartic acid         G         514.0
121  1224                             Glutamic acid         G         515.0
122  1225                                   Glycine         G         516.0
123  1226                                   Proline         G         517.0
124  1227                                    Serine         G         518.0
125  1228                            Hydroxyproline         G         521.0
126  1232                                  Cysteine         G         526.0
127  1233                                 Glutamine         G         528.0
128  1234                                   Taurine         G         529.0
129  1235                             Sugars, added         G         539.0
130  1242                          Vitamin E, added        MG         573.0
131  1246                       Vitamin B-12, added        UG         578.0
132  1253                               Cholesterol        MG         601.0
133  1257                  Fatty acids, total trans         G         605.0
134  1258              Fatty acids, total saturated         G         606.0
135  1259                                       4:0         G         607.0
136  1260                                       6:0         G         608.0
137  1261                                       8:0         G         609.0
138  1262                                      10:0         G         610.0
139  1263                                      12:0         G         611.0
140  1264                                      14:0         G         612.0
141  1265                                      16:0         G         613.0
142  1266                                      18:0         G         614.0
143  1267                                      20:0         G         615.0
144  1268                                      18:1         G         617.0
145  1269                                      18:2         G         618.0
146  1270                                      18:3         G         619.0
147  1271                                      20:4         G         620.0
148  1272                            22:6 n-3 (DHA)         G         621.0
149  1273                                      22:0         G         624.0
150  1274                                      14:1         G         625.0
151  1275                                      16:1         G         626.0
152  1276                                      18:4         G         627.0
153  1277                                      20:1         G         628.0
154  1278                            20:5 n-3 (EPA)         G         629.0
155  1279                                      22:1         G         630.0
156  1280                            22:5 n-3 (DPA)         G         631.0
157  1281                                    14:1 t         G         821.0
158  1283                              Phytosterols        MG         636.0
159  1285                              Stigmasterol        MG         638.0
160  1286                               Campesterol        MG         639.0
161  1287                            Brassicasterol        MG         640.0
162  1288                           Beta-sitosterol        MG         641.0
163  1289                               Campestanol        MG         642.0
164  1292        Fatty acids, total monounsaturated         G         645.0
165  1293        Fatty acids, total polyunsaturated         G         646.0
166  1294                           Beta-sitostanol        MG         647.0
167  1296                       Delta-5-avenasterol        MG         649.0
168  1298                       Phytosterols, other        MG         651.0
169  1299                                      15:0         G         652.0
170  1300                                      17:0         G         653.0
171  1301                                      24:0         G         654.0
172  1303                                    16:1 t         G         662.0
173  1304                                    18:1 t         G         663.0
174  1305                                    22:1 t         G         664.0
175  1306                18:2 t not further defined         G         665.0
176  1307                                    18:2 i         G         666.0
177  1310                                  18:2 t,t         G         669.0
178  1311                                 18:2 CLAs         G         670.0
179  1312                                    24:1 c         G         671.0
180  1313                              20:2 n-6 c,c         G         672.0
181  1314                                    16:1 c         G         673.0
182  1315                                    18:1 c         G         674.0
183  1316                              18:2 n-6 c,c         G         675.0
184  1317                                    22:1 c         G         676.0
185  1321                            18:3 n-6 c,c,c         G         685.0
186  1323                                      17:1         G         687.0
187  1325                                      20:3         G         689.0
188  1329        Fatty acids, total trans-monoenoic         G         693.0
189  1330          Fatty acids, total trans-dienoic         G         694.0
190  1331        Fatty acids, total trans-polyenoic         G         695.0
191  1332                                      13:0         G         696.0
192  1333                                      15:1         G         697.0
193  1334                                      22:2         G         698.0
194  1335                                      11:0         G         699.0
195  1368                Epigallocatechin-3-gallate        MG         753.0
196  1403                                    Inulin         G         806.0
197  1404                      18:3 n-3 c,c,c (ALA)         G         851.0
198  1405                                  20:3 n-3         G         852.0
199  1406                                  20:3 n-6         G         853.0
200  1408                                  20:4 n-6         G         855.0
201  1409                                     18:3i         G         856.0
202  1410                                      21:5         G         857.0
203  1411                                      22:4         G         858.0
204  1412                     18:1-11 t (18:1t n-7)         G         859.0
205  1414                                  20:3 n-9         G         861.0
206  2000              Sugars, total including NLEA         G         269.0
207  2003                                       5:0         G         632.0
208  2004                                       7:0         G         633.0
209  2005                                       9:0         G         634.0
210  2006                                      21:0         G         681.0
211  2007                                      23:0         G         682.0
212  2008                                      12:1         G         635.0
213  2009                                    14:1 c         G         822.0
214  2010                                    17:1 c         G         825.0
215  2012                                    20:1 c         G         829.0
216  2013                                    20:1 t         G         830.0
217  2014                                  22:1 n-9         G         676.1
218  2015                                 22:1 n-11         G         676.2
219  2016                                    18:2 c         G         831.0
220  2018                                    18:3 c         G         833.0
221  2019                                    18:3 t         G         834.0
222  2020                                    20:3 c         G         835.0
223  2021                                      22:3         G         683.0
224  2022                                    20:4 c         G         836.0
225  2023                                    20:5 c         G         837.0
226  2024                                    22:5 c         G         838.0
227  2025                                    22:6 c         G         839.0
228  2026                                    20:2 c         G         840.0
229  2028                       trans-beta-Carotene        UG         321.2
230  2029                            trans-Lycopene        UG         337.2
231  2032                      Cryptoxanthin, alpha        UG         335.0

         rank
0       500.0
1       600.0
2       800.0
3      1110.0
4      1000.0
5       300.0
6      2200.0
7      1600.0
8      1700.0
9      1800.0
10     1900.0
11     2000.0
12    18200.0
13   999999.0
14     2900.0
15     4100.0
16     1120.0
17      100.0
18     2600.0
19    18300.0
20    18400.0
21      400.0
22     1500.0
23        NaN
24     2100.0
25     2700.0
26     1200.0
27   999999.0
28     1240.0
29     1260.0
30      900.0
31   999999.0
32     5300.0
33   999999.0
34     5400.0
35     5500.0
36     5600.0
37     5700.0
38     5800.0
39     6241.0
40     5900.0
41   999999.0
42     6244.0
43     6000.0
44     6240.0
45     6150.0
46     6100.0
47     6243.0
48     6200.0
49     7500.0
50     7430.0
51     7420.0
52     7440.0
53     7450.0
54     7905.0
55     8650.0
56     8710.0
57     8720.0
58     8730.0
59     8700.0
60     7570.0
61     7580.0
62     7564.0
63     7460.0
64     7562.0
65     7530.0
66     7560.0
67   999999.0
68     8000.0
69     8100.0
70     8200.0
71     8300.0
72     8400.0
73     8500.0
74     8600.0
75     6245.0
76     6242.0
77     7800.0
78     7442.0
79     7532.0
80     7561.0
81     6300.0
82     6400.0
83     6500.0
84     6600.0
85     6700.0
86     6800.0
87   999999.0
88     6900.0
89     7300.0
90     7220.0
91     2800.0
92     8950.0
93     8900.0
94     8800.0
95     7000.0
96     7100.0
97   999999.0
98     7200.0
99   999999.0
100  999999.0
101    7230.0
102    7240.0
103    7250.0
104    7260.0
105    7290.0
106    7270.0
107   16300.0
108   16400.0
109   16500.0
110   16600.0
111   16700.0
112   16800.0
113   16900.0
114   17000.0
115   17100.0
116   17200.0
117   17300.0
118   17400.0
119   17500.0
120   17600.0
121   17700.0
122   17800.0
123   17900.0
124   18000.0
125   18100.0
126  999999.0
127  999999.0
128  999999.0
129    1540.0
130    7920.0
131    7340.0
132   15700.0
133   15400.0
134    9700.0
135    9800.0
136    9900.0
137   10000.0
138   10100.0
139   10300.0
140   10500.0
141   10700.0
142   10900.0
143   11100.0
144   12100.0
145   13100.0
146   13900.0
147   14700.0
148   15300.0
149   11200.0
150   11500.0
151   11700.0
152   14250.0
153   12400.0
154   15000.0
155   12500.0
156   15200.0
157   15510.0
158   15800.0
159   15900.0
160   16000.0
161   16100.0
162   16200.0
163   16221.0
164   11400.0
165   12900.0
166   16221.0
167   16221.0
168   16221.0
169   10600.0
170   10800.0
171   11300.0
172   15520.0
173   15521.0
174   15550.0
175   15610.0
176   13350.0
177   15615.0
178   13300.0
179   12800.0
180   14300.0
181   11800.0
182   12200.0
183   13200.0
184   12600.0
185   14100.0
186   12000.0
187   14400.0
188   15500.0
189   15601.0
190   15619.0
191   10400.0
192   11600.0
193   15100.0
194   10200.0
195   20700.0
196  999999.0
197   14000.0
198   14500.0
199   14600.0
200   14900.0
201   14200.0
202   15100.0
203   15160.0
204   12310.0
205   14650.0
206    1510.0
207    9850.0
208    9950.0
209   10050.0
210   11150.0
211   11250.0
212   11450.0
213   11501.0
214   12001.0
215   12401.0
216   15540.0
217   12601.0
218   12602.0
219   13150.0
220   13910.0
221   15660.0
222   14450.0
223   14675.0
224   14750.0
225   14950.0
226   15150.0
227   15250.0
228   14250.0
229    7444.0
230    7534.0
231    7461.0

In [28]:
#pd.set_option('display.max_rows', 10)

In [29]:
nutrients_base = [
    1008, # Energy (Kcal)
    1003, # Protein
    1004, # Total lipid (fat)
    1005, # Carbohydrate, by difference
    1050, # Carbohydrate, by summation
    1051, # Water
    1079, # Fiber, total dietary
    1087, # Calcium
    1090, # Magnesium
    1092, # Potassium
    1093, # Sodium
    1114, # Vitamin D
    1162, # Vitamin C
    1166, # Riboflavin
]

In [52]:
base_nutrients = nutrients[nutrients['id'].isin(nutrients_base)]
base_nutrients

      id                            name unit_name  nutrient_nbr    rank
1   1003                         Protein         G         203.0   600.0
2   1004               Total lipid (fat)         G         204.0   800.0
3   1005     Carbohydrate, by difference         G         205.0  1110.0
5   1008                          Energy      KCAL         208.0   300.0
16  1050      Carbohydrate, by summation         G         205.2  1120.0
17  1051                           Water         G         255.0   100.0
26  1079            Fiber, total dietary         G         291.0  1200.0
32  1087                     Calcium, Ca        MG         301.0  5300.0
35  1090                   Magnesium, Mg        MG         304.0  5500.0
37  1092                    Potassium, K        MG         306.0  5700.0
38  1093                      Sodium, Na        MG         307.0  5800.0
59  1114             Vitamin D (D2 + D3)        UG         328.0  8700.0
81  1162  Vitamin C, total ascorbic acid        MG         401.0  6300.0
83  1166                      Riboflavin        MG         405.0  6500.0

In [61]:
hummus = nutrient_hummus[nutrient_hummus['nutrient_id'].isin(nutrients_base)]
hummus = hummus.sort_values('nutrient_id')[['amount', 'nutrient_id']]
hummus

          amount  nutrient_id
4014789    7.350         1003
4014835   17.100         1004
4014836   14.900         1005
4014837  229.000         1008
4014863   13.900         1050
4014841   58.700         1051
4014796    5.400         1079
4014842   41.000         1087
4014798   71.100         1090
4014843  289.000         1092
4014800  438.000         1093
4014761    0.000         1162
4014763    0.115         1166

In [65]:
#base_nutrients['amount'] = nutrient_hummus['amount'].astype(float)
base = base_nutrients.merge(hummus, left_on='id', right_on='nutrient_id')
base[['name', 'amount', 'unit_name']]

                              name   amount unit_name
0                          Protein    7.350         G
1                Total lipid (fat)   17.100         G
2      Carbohydrate, by difference   14.900         G
3                           Energy  229.000      KCAL
4       Carbohydrate, by summation   13.900         G
5                            Water   58.700         G
6             Fiber, total dietary    5.400         G
7                      Calcium, Ca   41.000        MG
8                    Magnesium, Mg   71.100        MG
9                     Potassium, K  289.000        MG
10                      Sodium, Na  438.000        MG
11  Vitamin C, total ascorbic acid    0.000        MG
12                      Riboflavin    0.115        MG

In [73]:
for i, n in base.iterrows():
    print(n['name'])

Protein
Total lipid (fat)
Carbohydrate, by difference
Energy
Carbohydrate, by summation
Water
Fiber, total dietary
Calcium, Ca
Magnesium, Mg
Potassium, K
Sodium, Na
Vitamin C, total ascorbic acid
Riboflavin